# action.yml
name: 'Helm Validation Service'
description: 'Performs helm lint and template validation on specified charts'

inputs:
  chart-path:
    description: 'Path to the Helm chart'
    required: true
  values-file:
    description: 'Path to values file (optional)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.9.0'
      
    - name: Helm Lint
      shell: bash
      run: |
        echo "=== Starting Helm Validation ==="
        if [ -n "${{ inputs.values-file }}" ]; then
          helm lint ${{ inputs.chart-path }} -f ${{ inputs.values-file }}
        else
          helm lint ${{ inputs.chart-path }}
        fi
        echo "=== Validation Completed ==="

    - name: Generate Template Output for Changed Files
      if: github.event_name == 'pull_request'
      shell: bash
      id: template
      run: |
        # Fetch the necessary git history
        git fetch origin ${{ github.base_ref }}
        
        # Get list of changed files by comparing with base branch
        changed_files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '\.yaml$' || true)
        
        if [ -n "$changed_files" ]; then
          echo "Changed files detected: $changed_files"
          
          # Initialize template output
          TEMPLATE_OUTPUT="# Changed Files Templates\n\n"
          
          # Process each changed file
          for file in $changed_files; do
            if [[ -f "$file" ]]; then
              echo "Processing changes in: $file"
              TEMPLATE_OUTPUT+="## File: $file\n\n"
              
              if [ -n "${{ inputs.values-file }}" ]; then
                file_template=$(helm template ${{ inputs.chart-path }} -f ${{ inputs.values-file }} | grep -A1000 -B1000 "$(basename $file)" || true)
              else
                file_template=$(helm template ${{ inputs.chart-path }} | grep -A1000 -B1000 "$(basename $file)" || true)
              fi
              
              if [ -n "$file_template" ]; then
                TEMPLATE_OUTPUT+="$file_template\n\n---\n\n"
              fi
            fi
          done
          
          # Save template output
          echo "template<<EOF" >> $GITHUB_OUTPUT
          echo -e "$TEMPLATE_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "No YAML files changed in this PR."
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Comment on PR
      if: github.event_name == 'pull_request' && steps.template.outputs.has_changes == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const output = `## Helm Template Validation Results
          #### Chart Path: \`${{ inputs.chart-path }}\`
          
          <details><summary>Show Generated Kubernetes Manifests (Changed Files Only)</summary>
          
          \`\`\`yaml
          ${process.env.TEMPLATE}
          \`\`\`
          
          </details>`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
      env:
        TEMPLATE: ${{ steps.template.outputs.template }}