name: 'Helm Validation Service'
description: 'Performs helm lint and helm template on specified chart'
inputs:
  chart-path:
    description: 'Path to the Helm chart'
    required: true
  values-file:
    description: 'Path to values file (optional)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.9.0'
      
    - name: Helm Lint
      shell: bash
      run: |
        echo "=== Starting Helm Lint ==="
        if [ -n "${{ inputs.values-file }}" ]; then
          helm lint ${{ inputs.chart-path }} -f ${{ inputs.values-file }}
        else
          helm lint ${{ inputs.chart-path }}
        fi
        echo "=== Helm Lint Completed ==="
        
    - name: Helm Template
      shell: bash
      run: |
        echo "=== Starting Helm Template ==="
        echo "Generating Kubernetes manifests..."
        if [ -n "${{ inputs.values-file }}" ]; then
          echo "Using values file: ${{ inputs.values-file }}"
          helm template test-release ${{ inputs.chart-path }} -f ${{ inputs.values-file }}
        else
          echo "Using default values"
          helm template test-release ${{ inputs.chart-path }}
        fi
        echo "=== Helm Template Completed ==="