name: 'Helm Validation Service'
description: 'Performs helm lint and helm template on specified chart'
inputs:
  chart-path:
    description: 'Path to the Helm chart'
    required: true
  values-file:
    description: 'Path to values file (optional)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3
      
    - name: Helm Lint
      shell: bash
      run: |
        if [ -n "${{ inputs.values-file }}" ]; then
          helm lint ${{ inputs.chart-path }} -f ${{ inputs.values-file }}
        else
          helm lint ${{ inputs.chart-path }}
        fi
        
    - name: Helm Template
      shell: bash
      run: |
        if [ -n "${{ inputs.values-file }}" ]; then
          helm template ${{ inputs.chart-path }} -f ${{ inputs.values-file }}
        else
          helm template ${{ inputs.chart-path }}
        fi
