name: 'Test Action'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Test the action
      - uses: ./
        with:
          chart-path: './test/chart'  # You'll create this test chart
          values-file: './test/chart/values.yaml'
