# .github/workflows/test.yml
name: 'Test Action'
on:
  workflow_call:
    inputs:
      chart-path:
        description: 'Path to the Helm chart'
        required: true
        type: string
      values-file:
        description: 'Path to the values file'
        required: false
        type: string
        default: ''
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Test the action using inputs or default test paths
      - uses: ./
        with:
          chart-path: ${{ inputs.chart-path }}
          values-file: ${{ inputs.values-file }}